### ISSUE TITLE
Unable to Register of Office-hours.

### ISSUE THREAD

**Issue by ShubhamHiteshi** [OHIF/OHIF-Office-Hours#18]
Hello Team, 

Please let me know How can I join this meeting and where to register myself for the same ?

**Comment by abdou-chakhkhar** [comment]
I am encountering the same issue here

**Comment by huyng12** [comment]
Hi @sedghi , I cannot register also.

I clicked the link on README, and it opened Zoom application and asked for the password. Please help me with the registration.

Thank you so much!

**Comment by sedghi** [comment]
Can you try again now?

**Comment by huyng12** [comment]
> Can you try again now?

Yep, I can register now and registered.

Thank you so much for quick response 💯
